version: '2.0'
services:
  web:
    build: .
    ports:
        - '3000:3000'
    stdin_open: true
    restart: on-failure
    container_name: web-app
  #redis:
    #image: "redis:alpine"
volumes:
  logvolume01: {}
