version: '2.0'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
        - '3001:3001'
    
    stdin_open: true
    #restart: on-failure
    container_name: react-app

  #redis:
    #image: "redis:alpine"
volumes:
  logvolume01: {}
